export const LOAD_PROPTYPES = 'App/LOAD_PROPTYPES';
export const LOAD_PROPTYPES_SUCCESS = 'App/LOAD_PROPTYPES_SUCCESS';
export const LOAD_PROPTYPES_ERROR = 'App/LOAD_PROPTYPES_ERROR';

export const LOAD_AGGS = 'App/LOAD_AGGS';
export const LOAD_AGGS_SUCCESS = 'App/LOAD_AGGS_SUCCESS';
export const LOAD_AGGS_ERROR = 'App/LOAD_AGGS_ERROR';

export const LOAD_GEOS = 'App/LOAD_GEOS';
export const LOAD_GEOS_SUCCESS = 'App/LOAD_GEOS_SUCCESS';
export const LOAD_GEOS_ERROR = 'App/LOAD_GEOS_ERROR';
